'use strict';

module.exports = (app) => {

    app.get("/api/competition/all", (req, res) => {
        res.send([
        {
            "id": 1,
            "caption": "Ligue 1 2017/18",
            "league": "FL1",
            "year": "2017",
            "currentMatchday": 32,
            "numberOfMatchdays": 38,
            "numberOfGames": 380,
            "numberOfTeams": 20,
            "lastUpdated": 1523221805000
        }
    ]);
});

    app.get("/api/competition/:number/ranking/:matchday", (req, res) => {
        res.send({
      "id": 1,
      "leagueCaption": "Ligue 1 2017/18",
      "matchday": 1,
      "standing": [
        {
          "position": 1,
          "teamName": "Olympique Lyonnais",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/f/f1/Olympique_Lyon.svg",
          "points": 3,
          "goals": 4,
          "goalsAgainst": 0,
          "goalDifference": 4,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 2,
          "teamName": "Olympique de Marseille",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/2/27/Olympique_Marseille_Logo.svg",
          "points": 3,
          "goals": 3,
          "goalsAgainst": 0,
          "goalDifference": 3,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 2,
          "teamName": "OSC Lille",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/08/LOSC_Lille_Crest_2012.png",
          "points": 3,
          "goals": 3,
          "goalsAgainst": 0,
          "goalDifference": 3,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 4,
          "teamName": "EA Guingamp",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/a/ae/EA_Guingamp_Logo.svg",
          "points": 3,
          "goals": 3,
          "goalsAgainst": 1,
          "goalDifference": 2,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 5,
          "teamName": "Paris Saint-Germain",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/fr/8/86/Paris_Saint-Germain_Logo.svg",
          "points": 3,
          "goals": 2,
          "goalsAgainst": 0,
          "goalDifference": 2,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 6,
          "teamName": "AS Monaco FC",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/3/3c/AS_Monaco.svg",
          "points": 3,
          "goals": 3,
          "goalsAgainst": 2,
          "goalDifference": 1,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 7,
          "teamName": "AS Saint-Étienne",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/b1/AS_Saint-Etienne_(aktuell).svg",
          "points": 3,
          "goals": 1,
          "goalsAgainst": 0,
          "goalDifference": 1,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 7,
          "teamName": "Montpellier Hérault SC",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/3/35/HSC_Montpellier_Logo.svg",
          "points": 3,
          "goals": 1,
          "goalsAgainst": 0,
          "goalDifference": 1,
          "draws": 0,
          "losses": 0,
          "wins": 1
        },
        {
          "position": 9,
          "teamName": "Angers SCO",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/0f/SCO_Angers.svg",
          "points": 1,
          "goals": 2,
          "goalsAgainst": 2,
          "goalDifference": 0,
          "draws": 1,
          "losses": 0,
          "wins": 0
        },
        {
          "position": 9,
          "teamName": "FC Girondins de Bordeaux",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/e/ea/Girondins_Bordeaux_Logo.svg",
          "points": 1,
          "goals": 2,
          "goalsAgainst": 2,
          "goalDifference": 0,
          "draws": 1,
          "losses": 0,
          "wins": 0
        },
        {
          "position": 11,
          "teamName": "ES Troyes AC",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/commons/b/bf/ES_Troyes_AC.svg",
          "points": 1,
          "goals": 1,
          "goalsAgainst": 1,
          "goalDifference": 0,
          "draws": 1,
          "losses": 0,
          "wins": 0
        },
        {
          "position": 11,
          "teamName": "Stade Rennais FC",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/b6/Stade_Rennais_Football_Club.svg",
          "points": 1,
          "goals": 1,
          "goalsAgainst": 1,
          "goalDifference": 0,
          "draws": 1,
          "losses": 0,
          "wins": 0
        },
        {
          "position": 13,
          "teamName": "Toulouse FC",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/0a/FC_Toulouse_Logo.svg",
          "points": 0,
          "goals": 2,
          "goalsAgainst": 3,
          "goalDifference": -1,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 14,
          "teamName": "OGC Nice",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/fr/0/03/OGC_Nice_Logo.png",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 1,
          "goalDifference": -1,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 14,
          "teamName": "SM Caen",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/fr/7/79/LogoSmc2013.png",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 1,
          "goalDifference": -1,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 16,
          "teamName": "FC Metz",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/ba/FC_Metz_Logo.svg",
          "points": 0,
          "goals": 1,
          "goalsAgainst": 3,
          "goalDifference": -2,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 17,
          "teamName": "Amiens SC",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/de/0/0d/SC_Amiens_Logo.svg",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 2,
          "goalDifference": -2,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 18,
          "teamName": "Dijon FCO",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/e/e1/FCO_Dijon.svg",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 3,
          "goalDifference": -3,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 18,
          "teamName": "FC Nantes",
          "playedGames": 1,
          "crestURI": "http://upload.wikimedia.org/wikipedia/de/5/50/FC_Nantes_(seit_2008).svg",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 3,
          "goalDifference": -3,
          "draws": 0,
          "losses": 1,
          "wins": 0
        },
        {
          "position": 20,
          "teamName": "RC Strasbourg Alsace",
          "playedGames": 1,
          "crestURI": "https://upload.wikimedia.org/wikipedia/de/8/84/Racing_Club_Strasbourg.svg",
          "points": 0,
          "goals": 0,
          "goalsAgainst": 4,
          "goalDifference": -4,
          "draws": 0,
          "losses": 1,
          "wins": 0
        }
      ]
    })
    });

    app.get("/api/competition/:number/ranking", (req, res) => {
        res.send({
        "id": 33,
        "leagueCaption": "Ligue 1 2017/18",
        "matchday": 33,
        "standing": [
          {
            "position": 1,
            "teamName": "Paris Saint-Germain",
            "playedGames": 32,
            "crestURI": "https://upload.wikimedia.org/wikipedia/fr/8/86/Paris_Saint-Germain_Logo.svg",
            "points": 84,
            "goals": 96,
            "goalsAgainst": 22,
            "goalDifference": 74,
            "draws": 3,
            "losses": 2,
            "wins": 27
          },
          {
            "position": 2,
            "teamName": "AS Monaco FC",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/3/3c/AS_Monaco.svg",
            "points": 70,
            "goals": 77,
            "goalsAgainst": 34,
            "goalDifference": 43,
            "draws": 7,
            "losses": 4,
            "wins": 21
          },
          {
            "position": 3,
            "teamName": "Olympique Lyonnais",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/f/f1/Olympique_Lyon.svg",
            "points": 63,
            "goals": 69,
            "goalsAgainst": 36,
            "goalDifference": 33,
            "draws": 9,
            "losses": 5,
            "wins": 18
          },
          {
            "position": 4,
            "teamName": "Olympique de Marseille",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/2/27/Olympique_Marseille_Logo.svg",
            "points": 63,
            "goals": 64,
            "goalsAgainst": 38,
            "goalDifference": 26,
            "draws": 9,
            "losses": 5,
            "wins": 18
          },
          {
            "position": 5,
            "teamName": "Stade Rennais FC",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/b6/Stade_Rennais_Football_Club.svg",
            "points": 47,
            "goals": 41,
            "goalsAgainst": 38,
            "goalDifference": 3,
            "draws": 8,
            "losses": 11,
            "wins": 13
          },
          {
            "position": 6,
            "teamName": "OGC Nice",
            "playedGames": 33,
            "crestURI": "https://upload.wikimedia.org/wikipedia/fr/0/03/OGC_Nice_Logo.png",
            "points": 47,
            "goals": 44,
            "goalsAgainst": 45,
            "goalDifference": -1,
            "draws": 8,
            "losses": 12,
            "wins": 13
          },
          {
            "position": 7,
            "teamName": "Montpellier Hérault SC",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/3/35/HSC_Montpellier_Logo.svg",
            "points": 46,
            "goals": 31,
            "goalsAgainst": 26,
            "goalDifference": 5,
            "draws": 16,
            "losses": 6,
            "wins": 10
          },
          {
            "position": 8,
            "teamName": "FC Nantes",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/5/50/FC_Nantes_(seit_2008).svg",
            "points": 44,
            "goals": 31,
            "goalsAgainst": 35,
            "goalDifference": -4,
            "draws": 8,
            "losses": 12,
            "wins": 12
          },
          {
            "position": 9,
            "teamName": "AS Saint-Étienne",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/b1/AS_Saint-Etienne_(aktuell).svg",
            "points": 43,
            "goals": 37,
            "goalsAgainst": 45,
            "goalDifference": -8,
            "draws": 10,
            "losses": 11,
            "wins": 11
          },
          {
            "position": 10,
            "teamName": "EA Guingamp",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/a/ae/EA_Guingamp_Logo.svg",
            "points": 41,
            "goals": 36,
            "goalsAgainst": 46,
            "goalDifference": -10,
            "draws": 8,
            "losses": 13,
            "wins": 11
          },
          {
            "position": 11,
            "teamName": "Dijon FCO",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/e/e1/FCO_Dijon.svg",
            "points": 41,
            "goals": 45,
            "goalsAgainst": 60,
            "goalDifference": -15,
            "draws": 8,
            "losses": 13,
            "wins": 11
          },
          {
            "position": 12,
            "teamName": "FC Girondins de Bordeaux",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/e/ea/Girondins_Bordeaux_Logo.svg",
            "points": 40,
            "goals": 36,
            "goalsAgainst": 42,
            "goalDifference": -6,
            "draws": 7,
            "losses": 14,
            "wins": 11
          },
          {
            "position": 13,
            "teamName": "Amiens SC",
            "playedGames": 32,
            "crestURI": "https://upload.wikimedia.org/wikipedia/de/0/0d/SC_Amiens_Logo.svg",
            "points": 37,
            "goals": 29,
            "goalsAgainst": 34,
            "goalDifference": -5,
            "draws": 7,
            "losses": 15,
            "wins": 10
          },
          {
            "position": 14,
            "teamName": "Angers SCO",
            "playedGames": 33,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/0f/SCO_Angers.svg",
            "points": 37,
            "goals": 38,
            "goalsAgainst": 44,
            "goalDifference": -6,
            "draws": 13,
            "losses": 12,
            "wins": 8
          },
          {
            "position": 15,
            "teamName": "SM Caen",
            "playedGames": 32,
            "crestURI": "https://upload.wikimedia.org/wikipedia/fr/7/79/LogoSmc2013.png",
            "points": 35,
            "goals": 23,
            "goalsAgainst": 42,
            "goalDifference": -19,
            "draws": 5,
            "losses": 17,
            "wins": 10
          },
          {
            "position": 16,
            "teamName": "RC Strasbourg Alsace",
            "playedGames": 32,
            "crestURI": "https://upload.wikimedia.org/wikipedia/de/8/84/Racing_Club_Strasbourg.svg",
            "points": 34,
            "goals": 38,
            "goalsAgainst": 57,
            "goalDifference": -19,
            "draws": 10,
            "losses": 14,
            "wins": 8
          },
          {
            "position": 17,
            "teamName": "Toulouse FC",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/0a/FC_Toulouse_Logo.svg",
            "points": 30,
            "goals": 29,
            "goalsAgainst": 44,
            "goalDifference": -15,
            "draws": 9,
            "losses": 16,
            "wins": 7
          },
          {
            "position": 18,
            "teamName": "ES Troyes AC",
            "playedGames": 32,
            "crestURI": "https://upload.wikimedia.org/wikipedia/commons/b/bf/ES_Troyes_AC.svg",
            "points": 29,
            "goals": 25,
            "goalsAgainst": 46,
            "goalDifference": -21,
            "draws": 5,
            "losses": 19,
            "wins": 8
          },
          {
            "position": 19,
            "teamName": "OSC Lille",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/08/LOSC_Lille_Crest_2012.png",
            "points": 28,
            "goals": 30,
            "goalsAgainst": 51,
            "goalDifference": -21,
            "draws": 7,
            "losses": 18,
            "wins": 7
          },
          {
            "position": 20,
            "teamName": "FC Metz",
            "playedGames": 32,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/ba/FC_Metz_Logo.svg",
            "points": 22,
            "goals": 29,
            "goalsAgainst": 63,
            "goalDifference": -34,
            "draws": 7,
            "losses": 20,
            "wins": 5
          }
        ]
      }
    );
});


}
